apiVersion: v1
kind: ConfigMap
metadata:
  name: iroha-configmap-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
data:
  admin.priv: |
    f101537e319568c765b2cc89698325604991dca57b9716b58016b253506cab70
  admin.pub: |
    313a07e6384776ed95447710d15e59148473ccfc052a681317a72a69f2a49910
  config.docker: |
    {
      "block_store_path" : "/tmp/block_store/",
      "torii_port" : 50051,
      "internal_port" : 10001,
      "pg_opt" : "host=some-postgres port=5432 user=postgres password=mysecretpassword",
      "max_proposal_size" : 10,
      "proposal_delay" : 5000,
      "vote_delay" : 5000,
      "mst_enable" : false,
      "mst_expiration_time" : 1440,
      "max_rounds_delay": 3000,
      "stale_stream_max_rounds": 2
    }
  genesis.block: |
    {
       "block_v1":{
         "payload":{
            "transactions":[
               {
                  "payload":{
                     "reducedPayload":{
                        "commands":[
                           {
                              "addPeer":{
                                 "peer":{
                                    "address":"127.0.0.1:10001",
                                    "peerKey":"bddd58404d1315e0eb27902c5d7c8eb0602c16238f005773df406bc191308929"
                                 }
                              }
                           },
                           {
                              "createRole":{
                                 "roleName":"admin",
                                 "permissions":[
                                    "can_add_peer",
                                    "can_add_signatory",
                                    "can_create_account",
                                    "can_create_domain",
                                    "can_get_all_acc_ast",
                                    "can_get_all_acc_ast_txs",
                                    "can_get_all_acc_detail",
                                    "can_get_all_acc_txs",
                                    "can_get_all_accounts",
                                    "can_get_all_signatories",
                                    "can_get_all_txs",
                                    "can_get_blocks",
                                    "can_get_roles",
                                    "can_read_assets",
                                    "can_remove_signatory",
                                    "can_set_quorum"
                                 ]
                              }
                           },
                           {
                              "createRole":{
                                 "roleName":"user",
                                 "permissions":[
                                    "can_add_signatory",
                                    "can_get_my_acc_ast",
                                    "can_get_my_acc_ast_txs",
                                    "can_get_my_acc_detail",
                                    "can_get_my_acc_txs",
                                    "can_get_my_account",
                                    "can_get_my_signatories",
                                    "can_get_my_txs",
                                    "can_grant_can_add_my_signatory",
                                    "can_grant_can_remove_my_signatory",
                                    "can_grant_can_set_my_account_detail",
                                    "can_grant_can_set_my_quorum",
                                    "can_grant_can_transfer_my_assets",
                                    "can_receive",
                                    "can_remove_signatory",
                                    "can_set_quorum",
                                    "can_transfer"
                                 ]
                              }
                           },
                           {
                              "createRole":{
                                 "roleName":"money_creator",
                                 "permissions":[
                                    "can_add_asset_qty",
                                    "can_create_asset",
                                    "can_receive",
                                    "can_transfer"
                                 ]
                              }
                           },
                           {
                              "createDomain":{
                                 "domainId":"test",
                                 "defaultRole":"user"
                              }
                           },
                           {
                              "createAsset":{
                                 "assetName":"coin",
                                 "domainId":"test",
                                 "precision":2
                              }
                           },
                           {
                              "createAccount":{
                                 "accountName":"admin",
                                 "domainId":"test",
                                 "publicKey":"313a07e6384776ed95447710d15e59148473ccfc052a681317a72a69f2a49910"
                              }
                           },
                           {
                              "createAccount":{
                                 "accountName":"test",
                                 "domainId":"test",
                                 "publicKey":"716fe505f69f18511a1b083915aa9ff73ef36e6688199f3959750db38b8f4bfc"
                              }
                           },
                           {
                              "appendRole":{
                                 "accountId":"admin@test",
                                 "roleName":"admin"
                              }
                           },
                           {
                              "appendRole":{
                                 "accountId":"admin@test",
                                 "roleName":"money_creator"
                              }
                           }
                        ],
                        "quorum":1
                     }
                  }
               }
            ],
            "txNumber":1,
            "height":"1",
            "prevBlockHash":"0000000000000000000000000000000000000000000000000000000000000000"
         }
       }
    }
